---
# ===============================================================
# packages: install the necessary packages
# ===============================================================

- include_vars: "defaults/main.yml"

- name: Install packages
  apt:
    pkg={{ item }}
    state=installed
  with_items: "{{ ansible_role_apache.packages }}"
  tags: packages
